---
# tasks file for dnf

######################################
### packages

- name: "Dnf: Swap libcurl-minimal"
  become: true
  ansible.builtin.shell: |
    dnf swap -y libcurl-minimal libcurl
  register: dnf_swap_libcurl
  changed_when: dnf_swap_libcurl.rc != 0
  when:
    - dnf_automatic_package_state != 'absent'

- name: "Dnf: Manage packages"
  become: true
  ansible.builtin.package:
    name: "{{ dnf_automatic_package }}"
    state: "{{ dnf_automatic_package_state }}"
  notify:
    - "Dnf: Restart"

######################################
### jobs

- name: "Dnf: Copy dnf-automatic config (dnf5)"
  become: true
  ansible.builtin.template:
    src: automatic.conf.j2
    dest: "{{ dnf_automatic_config_path }}"
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_facts.pkg_mgr == 'dnf5'
  notify:
    - "Dnf: Restart"

######################################
### services

- name: "Dnf: Manage services"
  become: true
  ansible.builtin.service:
    name: "{{ dnf_automatic_service_name }}"
    state: "{{ dnf_automatic_service_state }}"
    enabled: "{{ dnf_automatic_service_enabled }}"
  when:
    - dnf_automatic_package_state != 'absent'
