---
# handlers file for dnf

- name: "Dnf: Restart"
  become: true
  ansible.builtin.service:
    name: "{{ dnf_automatic_service_name }}"
    state: restarted
  when:
    - dnf_automatic_package_state != 'absent'
