---
argument_specs:
  main:
    short_description: The main entry point for the dotfiles role.
    options:
      dotfiles_package_state:
        type: str
        required: false
        choices:
          - present
          - absent
          - latest
        description: dotfiles_package_state

      dotfiles_package:
        type: list
        elements: str
        required: false
        description: dotfiles_package

      dotfiles_inputrc_state:
        type: str
        required: false
        choices:
          - present
          - absent
          - skip
        description: dotfiles_inputrc_state

      dotfiles_inputrc_file:
        type: str
        required: false
        description: dotfiles_inputrc_file

      dotfiles_bashprofile_enabled:
        type: bool
        required: false
        description: dotfiles_bashprofile_enabled
