---
# tasks file for user

######################################
### jobs

- name: "User: Check if variables file exists"
  ansible.builtin.stat:
    path: "vars/{{ ansible_os_family }}.yml"
  register: vars_file

- name: "User: Load variables file"
  ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
  when: vars_file.stat.exists

- name: "User: Manage group"
  become: true
  ansible.builtin.group:
    name: "{{ user_username }}"
    state: "{{ user_state }}"

- name: "User: Install mkpasswd"
  become: true
  ansible.builtin.package:
    name: "{{ user_mkpasswd_package }}"
    state: present

- name: "User: Hash password"
  ansible.builtin.command: mkpasswd {{ user_password }}
  register: hashed_user_password
  changed_when: hashed_user_password.rc != 0
  when:
    - user_password != "!"

- name: "User: Set hashed password"
  ansible.builtin.set_fact:
    hashed_user_password: "{{ hashed_user_password.stdout }}"
  when:
    - user_password != "!"

- name: "User: Manage user"
  become: true
  ansible.builtin.user:
    name: "{{ user_username }}"
    group: "{{ user_username }}"
    groups: "{{ user_groups | default({}) }}"
    password: "{{ hashed_user_password | default('!') }}"
    create_home: "{{ user_home | default({}) }}"
    shell: "{{ user_shell | default({}) }}"
    state: "{{ user_state }}"
