---
# defaults file for monitoring

monitoring_agent_arch: amd64
monitoring_agent_tag: v0.38.1
monitoring_agent_package_state: present
monitoring_agent_package:
  - https://github.com/grafana/agent/releases/download/{{
    monitoring_agent_tag }}/grafana-agent-flow-{{ monitoring_agent_tag }}-1.{{ monitoring_agent_arch }}.rpm

monitoring_agent_config_path: /etc/grafana-agent-flow.river
monitoring_agent_config_remoteserver_loki: http://127.0.0.1:3100/loki/api/v1/push
monitoring_agent_config_remoteserver_prometheus: http://127.0.0.1:9100/api/v1/push

monitoring_agent_service_name: grafana-agent-flow-root.service
monitoring_agent_service_path: /usr/lib/systemd/system/{{ monitoring_agent_service_name }}
monitoring_agent_service_state: started
monitoring_agent_service_enabled: true
