---
# tasks file for update

######################################
### jobs

- name: "Update: Update packages on RHEL-based systems"
  become: true
  ansible.builtin.dnf:
    name: "{{ update_package_names }}"
    state: latest
    update_only: true
    update_cache: true
    security: "{{ update_package_security_only }}"
    bugfix: "{{ update_package_bugfix_only }}"
  when: ansible_os_family == 'RedHat'

- name: Update packages on Debian-based systems
  ansible.builtin.apt:
    name: "{{ update_package_names }}"
    state: latest
    update_cache: true
    only_upgrade: true
  when: ansible_os_family == 'Debian'

- name: Update packages on Archlinux systems
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_os_family == 'Archlinux'
