---
argument_specs:
  main:
    short_description: The main entry point for the dnf role.
    options:
      dnf_automatic_service_name:
        type: str
        required: false
        description: dnf_automatic_service_name

      dnf_automatic_service_state:
        type: str
        required: false
        choices:
          - reloaded
          - restarted
          - started
          - stopped
        description: dnf_automatic_service_state

      dnf_automatic_service_enabled:
        type: bool
        required: false
        description: dnf_automatic_service_enabled

      dnf_automatic_package_state:
        type: str
        required: false
        choices:
          - present
          - absent
          - latest
        description: dnf_automatic_package_state

      dnf_automatic_package:
        type: list
        elements: str
        required: false
        description: dnf_automatic_package
