---
dependency:
  name: galaxy
driver:
  name: podman
provisioner:
  name: ansible
platforms:
  - name: fedora
    image: docker.io/library/fedora:39
  - name: ubuntu
    image: docker.io/library/ubuntu:22.04
  - name: almalinux
    image: docker.io/library/almalinux:9
