---
argument_specs:
  main:
    short_description: The main entry point for the user role.
    options:
      user_username:
        type: str
        required: true
        description: user_username

      user_groups:
        type: list
        elements: str
        required: false
        description: user_groups

      user_password:
        type: str
        required: false
        description: user_password

      user_home:
        type: bool
        required: false
        description: user_home

      user_shell:
        type: str
        required: false
        description: user_shell

      user_state:
        type: str
        required: false
        choices:
          - present
          - absent
        description: user_state

      user_mkpasswd_package:
        type: list
        required: false
        description: user_mkpasswd_package
